--
- hosts: hostname
  user: root
  tasks:
   - name: installing httpd
     action: yum name=httpd state=installed
   - name: copy repo file
     copy: scr=index.html dest=/var/www/html/index.html
   - name: start apache
     service: 
      name: httpd
      state: restarted
   - uri: url=https://hostname

   - action: uri url=https://hostname return_content=yes
     register: webpage

   - action: fail
     when: "'Hello World' not in webpage.content"

